name: espn_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  dotted_border: ^2.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  cached_network_image: ^3.4.1
  table_calendar: ^3.1.3
  mocktail: ^1.0.4
  lock_orientation_screen: ^0.0.4
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  storybook_flutter: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  generate: true
